

export enum CategoryIconKey {
  Food = 'food',
  Groceries = 'groceries',
  Cafe = 'cafe',
  Restaurant = 'restaurant',
  Transport = 'transport',
  Taxi = 'taxi',
  Fuel = 'fuel',
  Gas = 'gas',
  Shopping = 'shopping',
  Clothes = 'clothes',
  Market = 'market',
  Health = 'health',
  Medicine = 'medicine',
  Pharmacy = 'pharmacy',
  Doctor = 'doctor',
  Bills = 'bills',
  Utilities = 'utilities',
  Rent = 'rent',
  Internet = 'internet',
  Salary = 'salary',
  Freelance = 'freelance',
  Income = 'income',
  Other = 'other',
}
